//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskUtility
{
    using System;
    using System.Collections.Generic;
    
    public partial class Email
    {
        public long Id { get; set; }
        public string Subject { get; set; }
        public string Message { get; set; }
    
        public virtual UserCountryRole FromUserCountryRole { get; set; }
        public virtual EmailTemplate EmailTemplate { get; set; }
        public virtual UserCountryRole ToUserCountryRole { get; set; }
        public virtual UserCountryRole CCUserCountryRole2 { get; set; }
    }
}
