//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskUtility
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rule
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Rule()
        {
            this.Tasks = new HashSet<Task>();
            this.CarryForwardRules = new HashSet<CarryForwardRules>();
        }
    
        public long Id { get; set; }
        public string Name { get; set; }
        public short BusinessDay { get; set; }
        public bool isRemaining { get; set; }
    
        public virtual UserCountryRole UserCountryRole { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task> Tasks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CarryForwardRules> CarryForwardRules { get; set; }
        public virtual UserCountryRole UserCountryRole1 { get; set; }
    }
}
