//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskUtility
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaskStatus
    {
        public long Id { get; set; }
        public int TaskId { get; set; }
        public short StatusId { get; set; }
    
        public virtual Task Task { get; set; }
        public virtual Status Status { get; set; }
    }
}
